/* -------------------------------------------------------
   Atölye Galerisi (Atölyemizden Kareler)
   Yeni fotoğraf: "edu-09.jpeg" şeklinde ekleyin.
------------------------------------------------------- */
const EDU_IMAGES = [
  "edu-01.jpeg",
  "edu-02.jpeg",
  "edu-03.jpeg",
  "edu-04.jpeg",
  "edu-05.jpeg",
  "edu-06.jpeg",
  "edu-07.jpeg",
  "edu-08.jpeg",
];

/* -------------------------------------------------------
   Atölye Videoları (Atölyemizden Videolar)
   Yeni video: "video6.mp4" şeklinde ekleyin.
------------------------------------------------------- */
const VIDEOS = [
  "video1.mp4",
  "video2.mp4",
  "video3.mp4",
  "video4.mp4",
  "video5.mp4",
  "video6.mp4",
  "video7.mp4"
];

/* -------------------------------------------------------
   Pasta Sipariş Fotoğrafları
   Yeni fotoğraf eklemek için sadece buraya isim yazın.
   Örnek: "sales-29.jpeg"
------------------------------------------------------- */
const SALES_IMAGES = [
  "sales-01.jpeg",
  "sales-02.jpeg",
  "sales-03.jpeg",
  "sales-04.jpeg",
  "sales-05.jpeg",
  "sales-06.jpeg",
  "sales-07.jpeg",
  "sales-08.jpeg",
  "sales-09.jpeg",
  "sales-10.jpeg",
  "sales-11.jpeg",
  "sales-12.jpeg",
  "sales-13.jpeg",
  "sales-14.jpeg",
  "sales-15.jpeg",
  "sales-16.jpeg",
  "sales-17.jpeg",
  "sales-18.jpeg",
  "sales-19.jpeg",
  "sales-20.jpeg",
  "sales-21.jpeg",
  "sales-22.jpeg",
  "sales-23.jpeg",
  "sales-24.jpeg",
  "sales-25.jpeg",
  "sales-26.jpeg",
  "sales-27.jpeg",
  "sales-28.jpeg",
  "sales-29.jpeg",
  "sales-30.jpeg",
  "sales-31.jpeg",
  "sales-32.jpeg",
  "sales-33.jpeg",
  "sales-34.jpeg",
  "sales-35.jpeg",
  "sales-36.jpeg",
  "sales-37.jpeg",
  "sales-38.jpeg",
  "sales-39.jpeg",
  "sales-40.jpeg",
  "sales-41.jpeg",
  "sales-42.jpeg",
  "sales-43.jpeg",
  "sales-44.jpeg",
  "sales-45.jpeg",
  "sales-46.jpeg",
  "sales-47.jpeg",
  "sales-48.jpeg",
  "sales-49.jpeg",
  "sales-50.jpeg",
  "sales-51.jpeg",
  "sales-51.jpg",
  "sales-52.jpg",
  "sales-53.jpg",
  "sales-54.jpg",
  "sales-55.jpg",
  "sales-56.jpg",
  "sales-57.jpg",
  "sales-58.jpg",
  "sales-59.jpg",
  "sales-60.jpg",
  "sales-61.jpg",
  "sales-62.jpg",
  "sales-63.jpg",
  "sales-64.jpg",
  "sales-65.jpg",
  "sales-66.jpg",
  "sales-67.jpg",
  "sales-68.jpg",
  "sales-70.jpg",
  "sales-71.jpg",
  "sales-72.jpg",
  "sales-73.jpg",
  "makaron-wa-07.jpg",
  "makaron-wa-08.jpg",
  "makaron-wa-09.jpg",
  "makaron-wa-10.jpg",
  "makaron-wa-11.jpg",
  "makaron-wa-12.jpg",
  "cupcake-wa-04.jpg",
  "cupcake-wa-05.jpg",
  "cupcake-wa-06.jpg",
  "cupcake-wa-07.jpg",
  "cupcake-wa-08.jpg",
  "cupcake-wa-09.jpg",
  "cupcake-wa-10.jpg",
  "cupcake-wa-11.jpg",
  "cakepops-wa-02.jpg",
  "cakepops-wa-03.jpg",
  "cakepops-wa-04.jpg",
  "cakepops-wa-05.jpg",
  "spor-wa-03.jpg",
  "spor-wa-04.jpg",
  "spor-wa-05.jpg",
  "spor-wa-06.jpg",
  "spor-wa-07.jpg",
  "dugun-wa-04.jpg",
  "dugun-wa-05.jpg",
  "dugun-wa-06.jpg",
  "dugun-wa-07.jpg",
  "dugun-wa-08.jpg",
  "dugun-wa-09.jpg"
];
