/* -------------------------------------------------------
   Atölye Galerisi (Atölyemizden Kareler)
   Yeni fotoğraf: "edu-09.webp" şeklinde ekleyin.
------------------------------------------------------- */
const EDU_IMAGES = [
  "edu-01.webp",
  "edu-02.webp",
  "edu-03.webp",
  "edu-04.webp",
  "edu-05.webp",
  "edu-06.webp",
  "edu-07.webp",
  "edu-08.webp",
];

/* -------------------------------------------------------
   Atölye Videoları (Atölyemizden Videolar)
   Yeni video: "video6.mp4" şeklinde ekleyin.
------------------------------------------------------- */
const VIDEOS = [
  "video1.mp4",
  "video2.mp4",
  "video3.mp4",
  "video4.mp4",
  "video5.mp4",
  "video6.mp4",
  "video7.mp4"
];

/* -------------------------------------------------------
   Pasta Sipariş Fotoğrafları
   Yeni fotoğraf eklemek için sadece buraya isim yazın.
   Örnek: "sales-74.webp"
------------------------------------------------------- */
const SALES_IMAGES = [
  "sales-01.webp",
  "sales-02.webp",
  "sales-03.webp",
  "sales-04.webp",
  "sales-05.webp",
  "sales-06.webp",
  "sales-07.webp",
  "sales-08.webp",
  "sales-09.webp",
  "sales-10.webp",
  "sales-11.webp",
  "sales-12.webp",
  "sales-13.webp",
  "sales-14.webp",
  "sales-15.webp",
  "sales-16.webp",
  "sales-17.webp",
  "sales-18.webp",
  "sales-19.webp",
  "sales-20.webp",
  "sales-21.webp",
  "sales-22.webp",
  "sales-23.webp",
  "sales-24.webp",
  "sales-25.webp",
  "sales-26.webp",
  "sales-27.webp",
  "sales-28.webp",
  "sales-29.webp",
  "sales-30.webp",
  "sales-31.webp",
  "sales-32.webp",
  "sales-33.webp",
  "sales-34.webp",
  "sales-35.webp",
  "sales-36.webp",
  "sales-37.webp",
  "sales-38.webp",
  "sales-39.webp",
  "sales-40.webp",
  "sales-41.webp",
  "sales-42.webp",
  "sales-43.webp",
  "sales-44.webp",
  "sales-45.webp",
  "sales-46.webp",
  "sales-47.webp",
  "sales-48.webp",
  "sales-49.webp",
  "sales-50.webp",
  "sales-51.webp",
  "sales-52.webp",
  "sales-53.webp",
  "sales-54.webp",
  "sales-55.webp",
  "sales-56.webp",
  "sales-57.webp",
  "sales-58.webp",
  "sales-59.webp",
  "sales-60.webp",
  "sales-61.webp",
  "sales-62.webp",
  "sales-63.webp",
  "sales-64.webp",
  "sales-65.webp",
  "sales-66.webp",
  "sales-67.webp",
  "sales-68.webp",
  "sales-70.webp",
  "sales-71.webp",
  "sales-72.webp",
  "sales-73.webp",
  "makaron-wa-07.webp",
  "makaron-wa-08.webp",
  "makaron-wa-09.webp",
  "makaron-wa-10.webp",
  "makaron-wa-11.webp",
  "makaron-wa-12.webp",
  "cupcake-wa-04.webp",
  "cupcake-wa-05.webp",
  "cupcake-wa-06.webp",
  "cupcake-wa-07.webp",
  "cupcake-wa-08.webp",
  "cupcake-wa-09.webp",
  "cupcake-wa-10.webp",
  "cupcake-wa-11.webp",
  "cakepops-wa-02.webp",
  "cakepops-wa-03.webp",
  "cakepops-wa-04.webp",
  "cakepops-wa-05.webp",
  "spor-wa-03.webp",
  "spor-wa-04.webp",
  "spor-wa-05.webp",
  "spor-wa-06.webp",
  "spor-wa-07.webp",
  "dugun-wa-04.webp",
  "dugun-wa-05.webp",
  "dugun-wa-06.webp",
  "dugun-wa-07.webp",
  "dugun-wa-08.webp",
  "dugun-wa-09.webp"
];
